FROM ubuntu:trusty

# Install basic packages
RUN apt-get update
RUN apt-get install -y build-essential wget curl git
RUN apt-get install -y zlib1g-dev libssl-dev libreadline-dev libyaml-dev libxml2-dev libxslt-dev
RUN apt-get install -y sqlite3 libsqlite3-dev
RUN apt-get clean

# start services
ADD lxc.conf /etc/init/lxc.conf

# timezone
RUN rm /etc/localtime
RUN ln -s /usr/share/zoneinfo/Asia/Tokyo /etc/localtime

# user
RUN useradd -m -s /bin/bash ubuntu
RUN yes ubuntu | passwd ubuntu
RUN echo "ubuntu  ALL=(ALL:ALL) NOPASSWD:ALL" > /etc/sudoers.d/ubuntu
RUN chmod 440 /etc/sudoers.d/ubuntu

# Install ruby-build
RUN git clone https://github.com/sstephenson/ruby-build.git .ruby-build
RUN .ruby-build/install.sh
RUN rm -fr .ruby-build

# Install ruby-2.1.2
RUN ruby-build 2.1.2 /usr/local

# Install bundler
RUN gem update --system
RUN gem install bundler --no-rdoc --no-ri

